Add Repositories list in Function view
kyma-project/console pull request #1954
Opened 2020-09-02 14:52 UTC by magicmatatjahu

**Description**

Changes proposed in this pull request:

As in title: Add Repositories list in Function view and tests for that.

**Related issue(s)**
https://github.com/kyma-project/console/issues/1932

2020-09-07 11:08 UTC, aerfio requested changes
There are few bugs:
- after changing anything in that modal "create" button becomes enabled, when there's no repository CR
![image](https://user-images.githubusercontent.com/17271979/92368655-4cd7fb00-f0f8-11ea-9362-12cff323070e.png)
- css:
![image](https://user-images.githubusercontent.com/17271979/92370707-f02a0f80-f0fa-11ea-9919-f16a12a0a290.png)
- this one is buggy, it allows me to create fn, bug crashes on cbs side
![image](https://user-images.githubusercontent.com/17271979/92371051-6d558480-f0fb-11ea-95be-420ebbcad35e.png)
- besides, to see those errors I had to type in something and then remove that...
![image](https://user-images.githubusercontent.com/17271979/92371238-a7268b00-f0fb-11ea-8882-2bf03814e149.png)
- we'd have to add logs from that job, that fetches gitrepo to that minimalised LogsUI, because if I supply wrong values I have no way to tell what went wrong

2020-09-07 12:18 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/RepositoryConfig/RepositoryConfig.js
> +    setStatus('');
I don't understand

2020-09-07 12:29 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/components/DropdownInput/DropdownInput.js
> +  const df = defaultValue === undefined ? options[0].value : defaultValue;
> `and what if options[0] doesn't exist` 

See the `if` above

> and you've set default value of defaultValue (use more descriptive name) to "", so undefined supplied to that component is always overridden by ""

It's an intentional logic :) Sometimes form needs a empty string (not null or undefined).

2020-09-08 10:39 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        INLINE_HELP: `Select type of Function's source. Available: Plain (code and dependencies is given as plain text) or Git (code and dependencies is fetched from git repository).`,
```suggestion
        INLINE_HELP: `Select the type of your Function's code source: Inline editor (code and dependencies are provided as plain text) or Git repository (code and dependencies are fetched from a Git repository).`,
```

2020-09-08 10:39 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +          KEY: 'Key',
```suggestion
          KEY: 'SSH key',
```

2020-09-08 10:39 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +      PLACEHOLDER: 'Reference',
```suggestion
      PLACEHOLDER: 'Enter a branch name or commit revision',
```

2020-09-08 10:39 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        PLACEHOLDER: 'Enter a reference',
```suggestion
        PLACEHOLDER: 'Enter a branch name or commit revision',
```

2020-09-08 10:39 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        PLACEHOLDER: 'Enter a base directory',
```suggestion
        PLACEHOLDER: 'Enter a base directory',
```

2020-09-08 10:39 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +      SUCCESS_MESSAGE: `Repository configuration for Function "{lambdaName}" were successfully updated`,
I would add commas at the end of all `SUCCESS_MESSAGE` & `ERROR_MESSAGE`.

2020-09-08 10:39 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +  KEY: 'Key',
```suggestion
  KEY: 'SSH key',
```

2020-09-08 10:47 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/constants.js
> +        INVALID: `Invalid Repository URL. The URL must start with one of the following prefixes: http(s), git, ssh.`,
```
Invalid Repository URL. The URL must starts with the "http(s)", "git", or "ssh" prefix and ends with the ".git" suffix.
```

2020-09-08 10:51 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/constants.js
> +    SUCCESS_MESSAGE: `Repository "{repositoryName}" was successfully created`,
We had `successfully` in all success messages :)

2020-09-08 10:52 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/constants.js
> +    SUCCESS_MESSAGE: `Repository "{repositoryName}" was successfully updated`,
We had successfully in all success messages :)

2020-09-08 10:52 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/constants.js
> +    SUCCESS_MESSAGE: `Repository "{repositoryName}" was successfully deleted`,
We had successfully in all success messages :)

2020-09-08 10:57 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/constants.js
> +        INLINE_HELP: `Reference to changes - branch or revision of commit.`,
Reference for source in repository :) branch or commit revision.

2020-09-08 11:36 UTC, magicmatatjahu commented
/test pre-console-core-ui

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        INLINE_HELP: `Select a Runtime on which your Function will run`,
```suggestion
        INLINE_HELP: `Runtime on which your Function will run`,
```

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        INLINE_HELP: `Select the type of your Function's code source: Inline editor (code and dependencies are provided as plain text) or Git repository (code and dependencies are fetched from a Git
```suggestion
        INLINE_HELP: `Type of your Function's code source: Inline editor (code and dependencies are provided as plain text) or Git repository (code and dependencies are fetched from a Git repository)`,
```

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +      INLINE_HELP: `Decide if you want to authenticate with your Git repository using token and password (Basic), authentication key (SSH key), or if you don't want to use any authorization method (P
```suggestion
      INLINE_HELP: `Authenticate with your Git repository using a token or password (Basic), an authentication key (SSH key), or don't use any authorization method (Public)`,
```

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +    SUCCESS_MESSAGE_MANY: `Event Triggers created successfully.`,
```suggestion
    SUCCESS_MESSAGE_MANY: `Event Triggers created.`,
```

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +    SUCCESS_MESSAGE_MANY: `Event Triggers created successfully.`,
I would remove "successfully" everywhere - it's not necessary and not recommended in guides. I know we had it everywhere before but it's time for changes :)

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        LABEL: 'Source type',
```suggestion
        LABEL: 'Source Type',
```

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        INVALID: `Invalid Repository URL. The URL must starts with the "http(s)", "git", or "ssh" prefix and ends with the ".git" suffix.`,
```suggestion
        INVALID: `Invalid Repository URL. The URL must start with the "http(s)", "git", or "ssh" prefix and end with the ".git" suffix.`,
```

2020-09-08 11:58 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        INVALID: `Invalid Repository URL. The URL must start with one of the following prefixes: http(s), git, ssh.`,
👍 I updated it correctly above.

2020-09-08 12:29 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/constants.js
> +    SUCCESS_MESSAGE_MANY: `Event Triggers created successfully.`,
Updated

2020-09-08 12:33 UTC, kazydek approved these changes

2020-09-08 12:39 UTC, magicmatatjahu commented
/test pre-console-core-ui

2020-09-08 12:41 UTC, magicmatatjahu commented
/test pre-console-compass

2020-09-08 12:50 UTC, magicmatatjahu commented
/test pre-console-core-ui

2020-09-08 14:03 UTC, magicmatatjahu commented
/test pre-console-compass

2020-09-09 06:52 UTC, magicmatatjahu commented
/test pre-console-core-ui

2020-09-10 10:57 UTC, aerfio submitted a review, later dismissed

2020-09-10 11:38 UTC, kazydek submitted a review, later dismissed

2020-09-10 12:59 UTC, Wawrzyn321 approved these changes

2020-09-10 13:17 UTC, magicmatatjahu commented
/test pre-console-core-ui

2020-09-10 13:29 UTC, magicmatatjahu commented
/test pre-console-core-ui

2020-09-10 14:24 UTC, aerfio approved these changes

2020-09-11 08:31 UTC, magicmatatjahu commented
/test pre-console-compass

2020-09-11 08:33 UTC, magicmatatjahu commented
/test pre-console-core-ui

2020-09-11 08:35 UTC, kazydek approved these changes

2020-09-14 07:37 UTC, magicmatatjahu commented
Merged in https://github.com/kyma-project/console/commit/ed03c5d3c31cc333c715149e22964e8022699b1a

2020-09-14 07:37 UTC, closed without merging