Configurable build resources in Function UI
kyma-project/console pull request #2000
Opened 2020-09-22 19:18 UTC by magicmatatjahu

**Description**

Changes proposed in this pull request:

- read proper minimal values from configmap
- read default values from configmap too (or change CBS in https://github.com/kyma-project/kyma/pull/9399/ to accept buildResources as null, and just let webhook do it's job)
**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9227

2020-09-25 12:37 UTC, aerfio requested changes

2020-09-25 12:37 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ConfigurationTab.js
> +  serviceCatalogExists = false,
wouldn't it be easier if we accepted `children` here and just inline those components in the parent? no playing with props this way

2020-09-25 12:37 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.scss
> +  box-shadow: none !important;
Is important really needed?

2020-09-25 12:37 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.scss
> +  > * {
be more specific than `*`

2020-09-25 12:38 UTC, aerfio requested changes

2020-09-25 12:38 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/shared.js
> +  Object.assign(schema, prepareSchema());
no return here?

2020-09-27 14:37 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.js
> +            {renderConfirmButton()}
I made it some 3 months ago and I unlined for readability.

2020-09-27 14:39 UTC, magicmatatjahu commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/shared.js
> +  Object.assign(schema, prepareSchema());
Nope. It operates on reference.

2020-10-01 21:50 UTC, aerfio commented
No longer relevant

2020-10-01 21:51 UTC, aerfio commented
Whoops wrong chrome tab 😛

2020-10-12 12:09 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        DESCRIPTION: `Choose one of predefined Function's resources values or compose your own values ​​by selecting the "Custom" option`,
```suggestion
        DESCRIPTION: `Choose one of the predefined values for Function's resources or set your own values ​​by selecting the "Custom" option.`,
```

2020-10-12 12:09 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        DESCRIPTION: `Choose one of predefined build Job's resources values or compose your own values ​​by selecting the "Custom" option`,
```suggestion
        DESCRIPTION: `Choose one of the predefined values for build Job's resources or set your own values ​​by selecting the "Custom" option.`,
```

2020-10-12 13:15 UTC, aerfio submitted a review, later dismissed

2020-10-12 13:29 UTC, kazydek approved these changes

2020-10-12 14:34 UTC, kazydek approved these changes

2020-10-12 14:56 UTC, aerfio approved these changes

2020-10-12 15:00 UTC, merged