Add a button to copy drawer content
kyma-project/console pull request #2006
Opened 2020-09-28 12:28 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- Add a button to copy drawer content
- Create a component for drawer with editor
- ...

**Related issue(s)**

2020-09-29 06:34 UTC, akucharska requested changes
For some strange after closing drawer you can't open it again

2020-09-29 06:34 UTC, akucharska commented on shared/components/SideDrawer/SideDrawer.js
> +          )}
There should be margin between those buttons.

2020-09-29 06:34 UTC, akucharska commented on shared/components/SideDrawer/SideDrawer.js
> +            <CopiableText textToCopy={textToCopy} iconOnly={true} />
Can we add text to copiable button co it looks like `<icon> Copy`?

2020-10-01 06:26 UTC, parostatkiem approved these changes
Well done 👌 
Left a few comments regarding propTypes.

2020-10-01 06:26 UTC, parostatkiem commented on shared/components/SideDrawer/SideDrawer.js
> +  bottomContent: PropTypes.any,
I think it could be `PropTypes.node` or at least `PropTypes.element`

2020-10-01 06:26 UTC, parostatkiem commented on shared/hooks/useSideDrawer.js
> +  initialContent: PropTypes.any.isRequired,
I don't think it's required. You can pass `undefined` and the drawer just won't show up.

2020-10-01 11:29 UTC, akucharska approved these changes

2020-10-05 12:27 UTC, dariadomagala commented
/retest

2020-10-06 08:06 UTC, parostatkiem approved these changes

2020-10-06 11:13 UTC, merged