Remove smoke tests for logs
kyma-project/console pull request #2010
Opened 2020-10-02 07:02 UTC by akucharska

**Description**

Changes proposed in this pull request:

- Remove LOG UI from Kyma installation in favour of deep-linking to grafana UI

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/9196

2020-10-05 12:34 UTC, Wawrzyn321 commented on shared/components/LogsLink/LogsLink.js
> +  }
I think we should add a `required` propType for the _domain_ (and maybe other props), as just rendering nothing if domain is falsy may be confusing.

2020-10-05 12:38 UTC, Wawrzyn321 commented on core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
> +
Why is the escape required? I removed it, and the link worked equally well.

2020-10-05 12:39 UTC, Wawrzyn321 commented on core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
> +import { getApiUrl } from '@kyma-project/common';
It'd be better to use `useConfig().fromConfig('domain')` instead of `getApiUrl`.

2020-10-05 12:42 UTC, Wawrzyn321 approved these changes
I've left some comments for the code, but anyway, it works really good!

2020-10-05 12:43 UTC, Wawrzyn321 requested changes
...

2020-10-05 12:47 UTC, akucharska commented on core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
> +
Without it job fails because of unnecessary \.

2020-10-05 12:51 UTC, Wawrzyn321 commented on core-ui/src/components/NamespaceDetails/NamespaceDetailsHeader/NamespaceDetailsHeader.js
> +
Yup, but don't we use just ``{namespace="${namespace.name}"}``?

2020-10-05 14:29 UTC, Wawrzyn321 requested changes

2020-10-05 14:29 UTC, Wawrzyn321 commented on shared/components/LogsLink/LogsLink.js
> +  query: PropTypes.string.isRequired,
Query shouldn't be `required`, if we are testing it in line 13.

2020-10-06 06:25 UTC, Wawrzyn321 approved these changes

2020-10-06 08:43 UTC, merged