Fix Lambda inline editor not showing up
kyma-project/console pull request #2045
Opened 2020-11-02 14:12 UTC by parostatkiem

**Description**

Changes proposed in this pull request:

- force redraw the editor on visibility change
- ...
- ...

**Related issue(s)**

2020-11-02 14:55 UTC, akucharska submitted a review, later dismissed

2020-11-03 09:23 UTC, akucharska submitted a review, later dismissed

2020-11-03 09:29 UTC, aerfio requested changes
LGTM, just 2 small changes needed

2020-11-03 09:29 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
> +      ); // eslint-disable-next-line react-hooks/exhaustive-deps
add `{` and `}` to that if and else

2020-11-03 09:29 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
> +      console.warn(
change that to error please, there's too many warnings that we ignore, and such a thing is important enough to be error

2020-11-03 09:31 UTC, parostatkiem commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
> +      console.warn(
I used warning intentionally. In my opinion it is definitely not an error. Whoever uses a stone-age browser has to be ready for an inconvenience 🤣

2020-11-03 09:45 UTC, aerfio approved these changes

2020-11-03 09:46 UTC, merged