Event Subscriptions
kyma-project/console pull request #2071
Opened 2020-12-11 12:47 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- Add Event Subscriptions depending on config variable

**Related issue(s)**
[Kyma](https://github.com/kyma-project/kyma/pull/10186)
[Bump](https://github.com/kyma-project/kyma/pull/10204)

2020-12-16 10:27 UTC, parostatkiem requested changes

2020-12-16 10:27 UTC, parostatkiem commented on core-ui/src/shared/components/EventSubscriptions/CreateSubscriptionModal.js
> +        content: `${EVENT_SUBSCRIPTION_PANEL.ADD_MODAL.NOTIFICATION.ERROR} ${e.message}`,
How about using `title` and `content` props? I think `title` also would be better in line 67.

2020-12-16 10:34 UTC, akucharska commented on core-ui/src/gql/queries.js
> +            eventType {
The naming is based on tunas structure

2020-12-16 11:40 UTC, parostatkiem submitted a review, later dismissed

2021-01-11 09:32 UTC, dariadomagala commented on core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
> +import EventTriggersWrapper from './Tabs/Configuration/EventTriggers/LambdaEventsWrapper';
Shouldn't that be
```suggestion
import LambdaEventsWrapper from './Tabs/Configuration/EventTriggers/LambdaEventsWrapper';
```
?

2021-01-11 09:32 UTC, dariadomagala commented on core-ui/src/components/Services/ServiceDetails/ServiceDetails.js
> +import ServiceEventTriggers from './ServiceEventTriggers/ServiceEventsWrapper';
Same here 
```suggestion
import ServiceEventsWrapper from './ServiceEventTriggers/ServiceEventsWrapper';
```

2021-01-11 13:45 UTC, Wawrzyn321 commented
/test pre-console-core-ui

2021-01-12 06:45 UTC, dariadomagala approved these changes

2021-01-12 10:15 UTC, aerfio approved these changes

2021-01-12 12:45 UTC, merged