Show function envs applied from ConfigMaps and Secrets
kyma-project/console pull request #2098
Opened 2021-01-21 18:43 UTC by kfurgol

**Description**

Changes proposed in this pull request:

- todo

**Related issue(s)**

2021-01-21 18:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/console?pullRequest=2098) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/console?pullRequest=2098) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/console?pullRequest=2098) it.</sub>

2021-01-25 14:52 UTC, kfurgol commented
/retest

2021-01-27 12:12 UTC, aerfio requested changes
LGTM for a first bigger React task :D but some changes are needed

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
> +    return customValueFromVariables.map(variable => {
make `customValueFromVariables` an argument to this function, do not operate on variables that just happen to be in scope (I see that the other function also works in a dirty way, if it's not so much work please change it too)

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
> +        };
to be more concise you can extract this object to be returned by some function, which accepts "type" argument which would be either "ConfigMap" or "Secret", because that's the only thing that changes here. DRY

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +  if (loading) return null;
```suggestion
  if (loading){
      return null;
  }    
```

in other places add `{` and `}` too

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +  if (error) return `Error: ${error}`;
add console.error(error) here

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +    return <span style={{ color: 'red' }}>{'The Secret does not exist!'}</span>;
Add this text to file with other texts managed by technical writers

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +        {'There is no such key in the Secret!'}
Add this text to file with other texts managed by technical writers

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +    <div className={!show ? 'blur-variable' : ''} onClick={_ => setShow(!show)}>
```suggestion
    <div className={!show ? 'blur-variable' : ''} onClick={_ => setShow(state => !state)}>
```
That's an alternate way to handle flipping the state, by supplying a function that gets current state and returns new one. It's a good practice and prevent subtle bugs.

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +  }
Same as before

2021-01-27 12:12 UTC, aerfio commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +    return <span style={{ color: 'red' }}>{'The Secret does not exist!'}</span>;
I can see you're using that component quite a bit -> extract this span with red color to external component, and do not use inline style, use whatever styling solution we're using in that part of console

2021-01-27 14:31 UTC, kfurgol commented on core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
> +    return <span style={{ color: 'red' }}>{'The Secret does not exist!'}</span>;
I've come up with another idea, what do you think about just returning `<FormMessage ...` with an `error` type?

2021-01-28 07:54 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        KEY_NOT_EXIST: 'There is no such key in the Config Map!',
```suggestion
        KEY_NOT_EXIST: 'There is no such key in the ConfigMap.',
```

2021-01-28 07:54 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        NOT_EXIST: 'The Config Map does not exist!',
```suggestion
        NOT_EXIST: 'ConfigMap does not exist.',
```

2021-01-28 07:54 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +      TOOLTIP_MESSAGE: 'This variable was applied from Config Map.',
```suggestion
      TOOLTIP_MESSAGE: 'This variable was applied from a ConfigMap.',
```

2021-01-28 07:54 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        NOT_EXIST: 'The Config Map does not exist!',
I think skipping "the" at the beginning of such short messages somehow looks better for the UI. We could also say `Related ConfigMap does not exist.`?

2021-01-28 07:54 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +      TOOLTIP_MESSAGE: 'This variable was applied from Secret.',
```suggestion
      TOOLTIP_MESSAGE: 'This variable was applied from a Secret.',
```

2021-01-28 07:54 UTC, kazydek commented on core-ui/src/components/Lambdas/constants.js
> +        NOT_EXIST: 'The Secret does not exist!',
or `Related...`, as above

2021-01-28 07:58 UTC, kfurgol commented on core-ui/src/components/Lambdas/constants.js
> +        NOT_EXIST: 'The Config Map does not exist!',
as you've said, let's keep this message short

2021-01-28 08:10 UTC, kazydek approved these changes

2021-01-28 08:14 UTC, kfurgol commented
/retest

2021-01-28 10:25 UTC, aerfio approved these changes

2021-01-28 10:53 UTC, merged