Move console outside of the Kyma cluster
kyma-project/console pull request #2121
Opened 2021-02-11 06:55 UTC by dariadomagala

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-02-15 09:08 UTC, Wawrzyn321 commented
/test pre-console-core-ui

2021-02-19 09:22 UTC, parostatkiem requested changes

2021-02-19 10:07 UTC, Wawrzyn321 commented on add-ons/nginx.conf
> +error_log stderr;
http://nginx.org/en/docs/ngx_core_module.html#error_log
```
The special value stderr selects the standard error file. 
```
https://stackoverflow.com/a/29951559
```
Don't use: /dev/stderr This will break your setup if you're going to use systemd-nspawn.
```
We don't use `systemd-nspawn`, but I'd go for `stderr` anyway.

2021-02-19 10:12 UTC, Wawrzyn321 commented on core-ui/nginx.conf
> +    listen 80;
Just checked it again to be sure, with `http2` a website returns 'invalid response'.

2021-02-19 12:19 UTC, parostatkiem approved these changes

2021-02-19 12:20 UTC, parostatkiem commented
/retest

2021-02-19 12:30 UTC, aerfio approved these changes

2021-02-19 12:37 UTC, merged