Rewrite functions to work with Pamela
kyma-project/console pull request #2135
Opened 2021-02-25 14:32 UTC by akucharska

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-02-26 11:53 UTC, parostatkiem requested changes

2021-02-26 11:53 UTC, parostatkiem commented on core-ui/src/components/Lambdas/gql/hooks/queries/useServiceQuery.js
> +    { pollingInterval: 3000000 },
Why this interval is so big?

2021-02-26 13:06 UTC, akucharska commented on core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
> +  const { data, error, loading = true } = useGet(
why?

2021-02-26 13:13 UTC, akucharska commented on core-ui/src/components/ApiRules/EditApiRule/EditApiRule.js
> +    { pollingInterval: 3000000 },
It is not necessary to update data so often i modal

2021-02-26 13:50 UTC, akucharska commented on core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
> +        generation: apiRule?.metadata?.generation || 1,
I don't think so

2021-02-26 14:26 UTC, parostatkiem commented on core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
> +  const { data, error, loading = true } = useGet(
Because the `data` word is very generic and can mean anything. We already know, at this moment, it'll be a list of _services_. Furthermore you can use the `useGetList` function which return the list itself instead of the `items` property and all the other useless metadata, also allows you filter the list right after the response is received and save some renders (you filter it later in the line #89).

2021-02-26 14:26 UTC, parostatkiem commented on core-ui/src/components/ApiRules/EditApiRule/EditApiRule.js
> +    { pollingInterval: 3000000 },
I guess it's also not necessary update it once every 50 minutes 😆

2021-03-01 14:18 UTC, parostatkiem submitted a review, later dismissed

2021-03-01 14:58 UTC, parostatkiem approved these changes

2021-03-01 15:43 UTC, aerfio approved these changes
LGTM

2021-03-02 07:08 UTC, kazydek approved these changes

2021-03-02 07:09 UTC, merged