Remove angular & components
kyma-project/console pull request #2142
Opened 2021-03-05 13:37 UTC by Wawrzyn321

**Description**

Changes proposed in this pull request:

- Remove Angular app from core
- Nuke 

**Related issue(s)**

2021-03-09 07:28 UTC, parostatkiem requested changes
I think the _scripts_ section in the `package.json` file needs some cleanup (we don't use .clusterConfig file anymore, do we?). Other than that, it looks good

2021-03-09 12:41 UTC, parostatkiem submitted a review, later dismissed

2021-03-10 07:58 UTC, majakurcius commented on core/README.md
> +Now you can access Console by name from the browser at `https://console.kyma.local`. A dedicated Docker container serves this application from inside the Kyma cluster.
Consider making this a link:
```suggestion
Now you can access Console by name from the browser at [`https://console.kyma.local`](https://console.kyma.local). A dedicated Docker container serves this application from inside the Kyma cluster.
```

2021-03-10 07:59 UTC, majakurcius submitted a review, later dismissed

2021-03-10 08:02 UTC, majakurcius submitted a review, later dismissed

2021-03-10 09:01 UTC, majakurcius approved these changes

2021-03-10 09:02 UTC, merged